---
  - name: Creating a repository file for Kubernetes packages
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding content in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: | 
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg 

  - name: Installing Kubernetes Binaries [ kubelet - kubectl - kubeadm ]
    yum:
     name: 
       - kubelet
       - kubectl
       - kubeadm
     state: present

  - name: to enable kubelet daemon and start the service
    systemd:
     name: "{{ item }}"
     daemon_reload: yes
     enabled: yes
     state: started
    loop: "{{ services }}"

  - name: Allow ports through firewall
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    loop: "{{ ports }}"

  - name: Firewall rule for enabling bridge networking
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"

  - name: Disabling Swap
    shell: swapoff -a

  - name: Commenting all swap entries
    replace:
      path: /etc/fstab
      regexp: '(.*swap*)'
      replace: '#\1'

...

