---
# tasks file for newrole
- import_tasks: docker.yml

- import_tasks: KubePkgs.yml
  
- import_tasks: master.yml
  delegate_to: localhost

- import_tasks: worker.yml
  when: ansible_hostname in groups["workers"]

- import_tasks: post.yml
  delegate_to: localhost
...
